#!/usr/bin/env python3
"""Regenerate ONE named golden case (document 06, "Deliberate update procedure").

Usage: python tests/fixtures/golden/update_fixture.py reference_10s_12lead

Prints the changed JSON pointers per profile and the summary byte count so the
review can cite them.  Bulk regeneration is intentionally unsupported.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2]))

CASES = {
    "reference_10s_12lead": {
        "purpose": "Pinned 10 s, 500 Hz, 12-lead, 10-beat case for the 24,000-byte summary contract and end-to-end drift detection",
        "sampling_rate": 500.0,
        "lead_names": ["I", "II", "III", "aVR", "aVL", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"],
        "input_mode": "standard_12",
        "config": {"input_mode": "standard_12", "fs_internal": None, "mains_frequency_hz": 50,
                   "st_amplitude_source": "analysis", "refinement": {}},
        "profiles": ["summary", "all", "debug"],
        "source": "Synthetic, generated by make_signal.py in this directory; no third-party data; redistributable with the repository.",
    },
}


def canonical(record) -> bytes:
    from ecgfeat import dumps_record

    return dumps_record(record)


def produce(case_id: str) -> dict[str, bytes]:
    from ecgfeat import ECGConfig, RefinementConfig, ecg_record

    spec = CASES[case_id]
    signal = np.load(HERE / case_id / "signal.npz")["signal"]
    config = dict(spec["config"])
    config["refinement"] = RefinementConfig(**config["refinement"])
    return {profile: canonical(ecg_record(signal, sampling_rate=spec["sampling_rate"], lead_names=spec["lead_names"],
                                          profile=profile, config=ECGConfig(**config)))
            for profile in spec["profiles"]}


def main(argv: list[str]) -> int:
    if len(argv) != 1 or argv[0] not in CASES:
        print(__doc__, file=sys.stderr)
        return 2
    case_id = argv[0]
    directory = HERE / case_id
    import ecgfeat
    from benchmarks.golden.compare import pointer_diff

    outputs = produce(case_id)
    signal_bytes = (directory / "signal.npz").read_bytes()
    signal = np.load(directory / "signal.npz")["signal"]
    manifest = {
        "case_id": case_id,
        **{k: v for k, v in CASES[case_id].items() if k != "profiles"},
        "signal_file_sha256": hashlib.sha256(signal_bytes).hexdigest(),
        "signal_sha256": hashlib.sha256(np.ascontiguousarray(signal, dtype="<f8").tobytes()).hexdigest(),
        "signal_shape": list(signal.shape),
        "schema_version": json.loads(outputs["summary"])["schema_version"],
        "library_version": json.loads(outputs["summary"])["provenance"]["library_version"],
        "records": {p: {"file": f"record.{p}.json", "sha256": hashlib.sha256(b).hexdigest(), "bytes": len(b)}
                    for p, b in outputs.items()},
    }
    for profile, data in outputs.items():
        target = directory / f"record.{profile}.json"
        if target.exists():
            diff = pointer_diff(json.loads(target.read_bytes()), json.loads(data), limit=10)
            print(profile, {k: diff[k] for k in ("changed", "removed", "added")}, [e["pointer"] for e in diff["examples"]])
        target.write_bytes(data)
    (directory / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"summary bytes: {manifest['records']['summary']['bytes']} (limit 24000)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
