"""Public facade with lazy imports; record-only use needs no numerical engine."""

from importlib import import_module

_EXPORTS = {
    "ECGFeatureExtractor": (".api", "ECGFeatureExtractor"),
    "to_dict": (".export", "to_dict"),
    "load_wfdb_mat": (".io", "load_wfdb_mat"),
    "parse_wfdb_header": (".io", "parse_wfdb_header"),
    "interpret": (".interpret", "interpret"),
    "plot_beat": (".visualize", "plot_beat"),
    "plot_beat_all_leads": (".visualize", "plot_beat_all_leads"),
    "plot_rep_beat": (".visualize", "plot_rep_beat"),
    "plot_quality_summary": (".visualize", "plot_quality_summary"),
    "ECGFeatures": (".models", "ECGFeatures"),
    "ECGInterpretation": (".models", "ECGInterpretation"),
    "GlobalFeatures": (".models", "GlobalFeatures"),
    "GroupFeatures": (".models", "GroupFeatures"),
    "LeadBeatFeatures": (".models", "LeadBeatFeatures"),
    "LeadQuality": (".models", "LeadQuality"),
    "PWaveBeatAssessment": (".models", "PWaveBeatAssessment"),
    "PWaveLeadBoundary": (".models", "PWaveLeadBoundary"),
    "PatientMeta": (".models", "PatientMeta"),
    "QRSDetectorResult": (".models", "QRSDetectorResult"),
    "QRSCandidateWindow": (".models", "QRSCandidateWindow"),
    "RepresentativeLeadFeatures": (".models", "RepresentativeLeadFeatures"),
    "STANDARD_12_LEADS": (".models", "STANDARD_12_LEADS"),
    "WaveBounds": (".models", "WaveBounds"),
    "PWaveConfig": (".p_wave_engine", "PWaveConfig"),
    "ECGInputError": (".errors", "ECGInputError"),
    "RefinementConfig": (".refinement", "RefinementConfig"),
    "ECGConfig": (".config", "ECGConfig"),
    "ExtractionConfig": (".config", "ExtractionConfig"),
    "LimitedInput": (".config", "LimitedInput"),
    "StandardInput": (".config", "StandardInput"),
    "AnalysisST": (".config", "AnalysisST"),
    "CalibratedPRST": (".config", "CalibratedPRST"),
    "AdaptivePRTPST": (".config", "AdaptivePRTPST"),
    "RecordPWaveConfig": (".config", "PWaveConfig"),
    "STAmplitudeSource": (".config", "STAmplitudeSource"),
    "config_provenance": (".config", "config_provenance"),
    "ECGInput": (".pipeline", "ECGInput"),
    "ECGMeasurements": (".pipeline", "ECGMeasurements"),
    "ECGRecordExtractor": (".pipeline", "ECGRecordExtractor"),
    "ecg_dump": (".pipeline", "ecg_dump"),
    "ecg_emit": (".pipeline", "ecg_emit"),
    "ecg_measure": (".pipeline", "ecg_measure"),
    "ecg_prepare": (".pipeline", "ecg_prepare"),
    "ecg_record": (".pipeline", "ecg_record"),
    "extract_ecg_record": (".pipeline", "extract_ecg_record"),
    "extract_record": (".pipeline", "extract_record"),
    "AddressResolution": (".record", "AddressResolution"),
    "AlgorithmFingerprint": (".record", "AlgorithmFingerprint"),
    "BeatView": (".record", "BeatView"),
    "ECGRecord": (".record", "ECGRecord"),
    "FieldValidation": (".record", "FieldValidation"),
    "InputFingerprint": (".record", "InputFingerprint"),
    "LeadView": (".record", "LeadView"),
    "MeasurementQuery": (".record", "MeasurementQuery"),
    "MeasurementProvenance": (".record", "MeasurementProvenance"),
    "MeasurementResult": (".record", "MeasurementResult"),
    "MeasurementSelection": (".record", "MeasurementSelection"),
    "Measured": (".record", "Measured"),
    "NotApplicable": (".record", "NotApplicable"),
    "NotApplicableAbsence": (".record", "NotApplicableAbsence"),
    "NullAbsence": (".record", "NullAbsence"),
    "RecordAddress": (".record", "RecordAddress"),
    "RecordSidecar": (".record", "RecordSidecar"),
    "SerializedRecord": (".record", "SerializedRecord"),
    "Unavailable": (".record", "Unavailable"),
    "UnmeasurableAbsence": (".record", "UnmeasurableAbsence"),
    "ValidationStatus": (".record", "ValidationStatus"),
    "build_record": (".record", "build_record"),
    "build_provenance": (".record", "build_provenance"),
    "dumps_record": (".record", "dumps_record"),
    "dump_measurements": (".record", "dump_measurements"),
    "encode_npz_sidecar": (".record", "encode_npz_sidecar"),
    "fingerprint_input": (".record", "fingerprint_input"),
    "iter_beats": (".record", "iter_beats"),
    "iter_leads": (".record", "iter_leads"),
    "load_record": (".record", "load_record"),
    "loads_record": (".record", "loads_record"),
    "make_record_address": (".record", "make_record_address"),
    "measured": (".record", "measured"),
    "not_applicable": (".record", "not_applicable"),
    "parse_address": (".record", "parse_address"),
    "parse_record_address": (".record", "parse_record_address"),
    "query_many": (".record", "query_many"),
    "query_measurement": (".record", "query_measurement"),
    "record_to_dict": (".record", "record_to_dict"),
    "resolve_address": (".record", "resolve_address"),
    "resolve_pointer": (".record", "resolve_pointer"),
    "select_measurements": (".record", "select_measurements"),
    "serialize_record": (".record", "serialize_record"),
    "to_json_obj": (".record", "to_json_obj"),
    "unavailable": (".record", "unavailable"),
    "validate_record": (".record", "validate_record"),
    "AddressNotFoundError": (".errors", "AddressNotFoundError"),
    "AddressSyntaxError": (".errors", "AddressSyntaxError"),
    "AmplitudeUnitError": (".errors", "AmplitudeUnitError"),
    "ComputationInvariantError": (".errors", "ComputationInvariantError"),
    "ConfigurationError": (".errors", "ConfigurationError"),
    "LeadNameError": (".errors", "LeadNameError"),
    "MeasurementNotFoundError": (".errors", "MeasurementNotFoundError"),
    "MeasurementSelectorError": (".errors", "MeasurementSelectorError"),
    "RecordIdentityError": (".errors", "RecordIdentityError"),
    "RecordValidationError": (".errors", "RecordValidationError"),
    "SamplingRateError": (".errors", "SamplingRateError"),
    "SignalShapeError": (".errors", "SignalShapeError"),
}

__all__ = list(_EXPORTS)


def __getattr__(name: str):
    try:
        module_name, symbol = _EXPORTS[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value = getattr(import_module(module_name, __name__), symbol)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))
