from __future__ import annotations

import re
import tempfile
import unittest
from pathlib import Path

import medgemma_ecg_core as core


class MedGemmaECGCoreTests(unittest.TestCase):
    def test_medgemma_runtime_uses_shared_8192_token_context_limit(self) -> None:
        import app
        import batch_medgemma_diagnostics as batch_script

        self.assertEqual(8192, core.DEFAULT_MODEL_MAX_LEN)
        self.assertEqual(2048, core.DEFAULT_MAX_OUTPUT_TOKENS)
        self.assertEqual(core.DEFAULT_MODEL_MAX_LEN, app.MODEL_MAX_LEN)
        self.assertEqual(core.DEFAULT_MODEL_MAX_LEN, batch_script.MODEL_MAX_LEN)
        self.assertEqual(core.DEFAULT_MAX_OUTPUT_TOKENS, app.MODEL_MAX_OUTPUT_TOKENS)
        self.assertEqual(core.DEFAULT_MAX_OUTPUT_TOKENS, batch_script.MODEL_MAX_OUTPUT_TOKENS)

    @staticmethod
    def _glasgow_v2() -> dict:
        return {
            "schema_version": "glasgow_rules.v2",
            "statement_resolution": {
                "summary_code": {"code": 5, "label": "Abnormal ECG"},
                "preliminary": [
                    {
                        "rule_id": "GAN-04.03-03",
                        "statement": "--- Interpretation made without knowing patient’s gender ---",
                        "fidelity": "glasgow_explicit",
                    }
                ],
                "final": [
                    {
                        "rule_id": "GAN-06.02-02",
                        "statement": "Prolonged QT – consider ischemia, electrolyte imbalance, drug effects",
                        "fidelity": "glasgow_explicit",
                    }
                ],
                "unavailable": [
                    {
                        "rule_id": "GAN-04.04-03",
                        "missing_inputs": ["metadata.similar_precordial_qrs"],
                    }
                ],
                "restricted_analysis": {"active": False, "stopped_by": []},
            },
        }

    def test_stale_glasgow_payload_is_ignored(self) -> None:
        data = {
            "global_features": {},
            "interpretation": {},
            "groups": {},
            "quality": {},
            "representative_leads": {},
            "metadata": {},
            "glasgow": self._glasgow_v2(),
        }

        summary = core.summarize_current_features(data, "en")

        self.assertNotIn("Glasgow", summary)
        self.assertNotIn("GAN-", summary)
        self.assertIn("Rhythm/interval interpretation", summary)

    def test_app_summary_ignores_stale_glasgow_context(self) -> None:
        import app

        data = {
            "global_features": {},
            "interpretation": {},
            "groups": {},
            "quality": {},
            "representative_leads": {},
            "metadata": {},
            "glasgow": self._glasgow_v2(),
        }

        summary = app._summarize_current_features(data, "en")

        self.assertNotIn("Glasgow", summary)
        self.assertNotIn("GAN-", summary)
        cleaned = app.sanitize_report_text(
            "Record ID : hidden\nHx : dataset=secret\nSx : hidden\nDx Codes : 1\nHeart Rate : 80 bpm"
        )
        self.assertNotIn("Record ID", cleaned)
        self.assertNotIn("dataset=secret", cleaned)
        self.assertNotIn("Sx", cleaned)
        self.assertIn("Heart Rate", cleaned)

    def test_sanitize_report_text_removes_label_bearing_lines(self) -> None:
        raw = """ECG MEASUREMENT REPORT
Record ID     : ami_generated_001
Dx Codes      : 12345
Dx Detail     : Acute myocardial infarction
Hx            : dataset=ptbxl; source=generated; disease=ami
Sx            : batch_id=ami_generated_001
Heart Rate    : 88 bpm
ST depression : V4:-0.120mV
NOTE: This report is generated by a research algorithm and has NOT
"""

        cleaned = core.sanitize_report_text(raw)

        self.assertIn("Heart Rate    : 88 bpm", cleaned)
        self.assertIn("ST depression : V4:-0.120mV", cleaned)
        self.assertNotIn("Record ID", cleaned)
        self.assertNotIn("Dx Codes", cleaned)
        self.assertNotIn("Dx Detail", cleaned)
        self.assertNotIn("Hx", cleaned)
        self.assertNotIn("Sx", cleaned)
        self.assertNotIn("disease=ami", cleaned.lower())
        self.assertNotIn("ami_generated_001", cleaned.lower())

    def test_build_context_summary_from_paths_keeps_ecg_features_but_not_dir_label(self) -> None:
        features = {
            "global_features": {
                "heart_rate_bpm": 113.0,
                "atrial_rate_bpm": 113.0,
                "pr_ms": 145.0,
                "qrs_ms": 70.0,
                "qt_ms": 370.0,
                "qtc_bazett_ms": 508.0,
                "qtc_fridericia_ms": 457.0,
                "qt_dispersion_ms": 202.0,
                "p_axis_deg": 73.0,
                "qrs_axis_deg": 17.0,
                "t_axis_deg": 75.0,
                "st_axis_deg": 35.0,
                "paced_rhythm": False,
            },
            "interpretation": {
                "rr_irregularity_class": "regular",
                "rr_cv": 0.0089,
                "probable_af": False,
                "heart_rate_class": "tachycardia",
                "pr_class": "normal",
                "qrs_width_class": "normal",
                "qtc_class": "prolonged",
                "avb_grade": None,
                "bundle_branch_block": None,
                "wpw_pattern": False,
                "p_morphology_class": "lae",
                "lae_suspected": True,
                "lae_definite": True,
                "ptf_v1_class": "definite_lae",
                "q_wave_territories": ["inferior"],
                "r_progression_class": "normal",
                "r_s_transition_lead": "V3",
                "st_elevation_leads": {},
                "st_depression_leads": {"V4": -0.12},
                "st_territories_elevated": [],
                "st_territories_depressed": ["anterior"],
                "reciprocal_change_detected": False,
                "tall_t_leads": [],
                "lvh_class": None,
                "lvh_voltage_criteria": [],
                "low_voltage_class": None,
                "rvh_suspected": False,
                "limb_reversal_suspected": False,
                "precordial_reversal_suspected": False,
            },
            "groups": {
                "1": {
                    "group_id": 1,
                    "member_count": 19,
                    "member_pct": 100.0,
                    "mean_rr_ms": 531.0,
                    "mean_qrs_ms": 66.0,
                    "flags": {"dominant_group": True},
                }
            },
            "quality": {
                "I": {
                    "reliable": True,
                    "flags": [],
                    "reliable_for_p": True,
                    "reliable_for_qrs": True,
                    "reliable_for_t": True,
                    "reliable_for_qt": True,
                },
                "II": {
                    "reliable": True,
                    "flags": [],
                    "reliable_for_p": True,
                    "reliable_for_qrs": True,
                    "reliable_for_t": True,
                    "reliable_for_qt": True,
                },
            },
            "representative_leads": {
                "I": {
                    "params": {
                        "pr_ms": 142.0,
                        "qrs_ms": 68.0,
                        "qt_ms": 450.0,
                        "r_amp_mv": 0.946,
                        "t_amp_mv": 0.046,
                        "st_on_mv": -0.016,
                    }
                },
                "II": {
                    "params": {
                        "pr_ms": 162.0,
                        "qrs_ms": 82.0,
                        "qt_ms": 442.0,
                        "r_amp_mv": 0.513,
                        "t_amp_mv": 0.057,
                        "st_on_mv": -0.084,
                    }
                },
            },
            "metadata": {
                "patient_meta": {"age": 64, "sex": "Female"},
                "input_fs": 100,
                "internal_fs": 500,
                "n_beats": 19,
                "reliable_qt_leads": ["V1", "V2", "V3"],
            },
        }
        report = """Record ID     : ami_generated_001
Hx            : disease=ami; source=generated
Heart Rate    : 113 bpm
ST depression : V4:-0.120mV
"""

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            features_path = root / "001_features.json"
            report_path = root / "001_report.txt"
            features_path.write_text(core.json_dumps(features), encoding="utf-8")
            report_path.write_text(report, encoding="utf-8")

            summary = core.build_context_summary_from_paths(features_path, report_path, "", "en")

        self.assertIn("HR 113.0 bpm", summary)
        self.assertIn("ST depression", summary)
        self.assertNotIn("disease=ami", summary.lower())
        self.assertNotIn("ami_generated_001", summary.lower())

    def test_build_prompt_contains_required_sections(self) -> None:
        prompt = core.build_prompt("example context", language="en")
        self.assertIn("### Most Likely Diagnosis", prompt)
        self.assertIn("### Similar Diagnoses (ranked by similarity)", prompt)
        self.assertIn("<start_of_turn>user", prompt)
        self.assertTrue(prompt.endswith("<start_of_turn>model\n"))

    def test_parse_medgemma_output_extracts_top1_and_similar(self) -> None:
        text = """### Most Likely Diagnosis
- Acute myocardial infarction

### Diagnostic Rationale
- ST depression with abnormal repolarization.

### Similar Diagnoses (ranked by similarity)
1. Diagnosis: Ischemia
   Shared features: ST-T abnormality
   Key differentiator: No infarction pattern
2. Diagnosis: Old myocardial infarction
   Shared features: Q-wave territory changes
   Key differentiator: Less acute repolarization change
3. Diagnosis: Left ventricular hypertrophy
   Shared features: Secondary ST-T changes
   Key differentiator: Voltage criteria

### Uncertainty and Review Priorities
- Review anterior leads."""

        parsed = core.parse_medgemma_output(text)

        self.assertEqual("Acute myocardial infarction", parsed["top1_raw"])
        self.assertEqual(
            ["Ischemia", "Old myocardial infarction", "Left ventricular hypertrophy"],
            parsed["similar_raw"],
        )
        self.assertIn("Review anterior leads.", parsed["uncertainty"])

    def test_normalize_diagnosis_maps_aliases_and_unknowns(self) -> None:
        self.assertEqual("acute myocardial infarction", core.normalize_diagnosis("AMI"))
        self.assertEqual("complete right bundle branch block", core.normalize_diagnosis("CRBBB"))
        self.assertEqual("normal ecg", core.normalize_diagnosis("normal sinus rhythm"))
        self.assertIsNone(core.normalize_diagnosis("unmapped phrase"))

    def test_ground_truth_mapping_covers_known_directory_labels(self) -> None:
        self.assertEqual("acute myocardial infarction", core.canonical_label_for_dir("ami"))
        self.assertEqual("normal ecg", core.canonical_label_for_dir("norm"))
        self.assertEqual("complete right bundle branch block", core.canonical_label_for_dir("crbbb"))

    def test_sanitize_report_text_strips_authoritative_rule_engine_block(self) -> None:
        raw = """  ───  PATIENT INFORMATION  ───────────────────────────────────────
  Age           : 82
  Dx Detail     : 164890007 (Atrial flutter); 233917008
                  (Atrioventricular block)
  Heart Rate    : 118 bpm

  ───  UNIFIED CLINICAL INTERPRETATION  [AUTHORITATIVE RULE OUTPUT]  ─
  Overall status : abnormal_with_limited_coverage
  CLIN-CONDUCTION-LAFB-01 : ECG pattern consistent with left
                         anterior fascicular block

  ───  RHYTHM SUMMARY  ────────────────────────────────────────────
  Total beats detected : 19
"""
        cleaned = core.sanitize_report_text(raw)

        self.assertIn("Heart Rate    : 118 bpm", cleaned)
        self.assertIn("RHYTHM SUMMARY", cleaned)
        self.assertIn("Total beats detected", cleaned)
        self.assertNotIn("Atrioventricular block", cleaned)
        self.assertNotIn("UNIFIED CLINICAL INTERPRETATION", cleaned)
        self.assertNotIn("CLIN-CONDUCTION-LAFB-01", cleaned)
        self.assertNotIn("fascicular block", cleaned)

    def test_sanitize_report_text_strips_retired_interpretation_blocks(self) -> None:
        raw = """  ───  BEAT-LEVEL QUALITY SUMMARY  (T004)  ────────────────────────
  Reliable-QT leads        : II, aVL

  ───  DXL-INSPIRED REFERENCE DETAIL  [REFERENCE ONLY — NOT FINAL]  ─
    ┌─ Step 3: Axis & Intervals
    │  QRS axis            : -76°  →  LAFB
    └  *** STEMI codes     : PMIA ***

  ───  GLASGOW MEASUREMENT MATRIX  (34 guide rows)  ─
  Row 1     : P onset [ms]
      I=2.000  II=110.000
"""
        cleaned = core.sanitize_report_text(raw)

        self.assertIn("Reliable-QT leads", cleaned)
        self.assertNotIn("GLASGOW MEASUREMENT MATRIX", cleaned)
        self.assertNotIn("Row 1", cleaned)
        self.assertNotIn("DXL-INSPIRED", cleaned)
        self.assertNotIn("STEMI codes", cleaned)
        self.assertNotIn("LAFB", cleaned)

    def test_summarize_layered_evidence_excludes_glasgow_and_clinical_conclusions(self) -> None:
        data = {
            "global_features": {"heart_rate_bpm": 58.0, "qrs_ms": 88.0},
            "interpretation": {"heart_rate_class": "bradycardia"},
            "quality": {},
            "representative_leads": {},
            "groups": {},
            "metadata": {},
            "glasgow": self._glasgow_v2(),
        }

        layers = core.summarize_layered_evidence(data, "en")

        combined = "\n".join(layers.values())
        self.assertIn("HR 58.0 bpm", combined)
        self.assertNotIn("Glasgow", combined)
        self.assertNotIn("Abnormal ECG", combined)

    def test_build_layered_prompt_forbids_external_conclusions_and_orders_layers(self) -> None:
        layers = {"L0": "quality ok", "L1": "sinus", "L2": "normal PR", "L3": "normal axis", "L4": "no Q waves"}
        prompt = core.build_layered_prompt(layers, "sample report", "", "en")

        self.assertIn("No output from any other automated diagnostic system", prompt)
        self.assertLess(prompt.index("### L0 Evidence"), prompt.index("### L1 Evidence"))
        self.assertLess(prompt.index("### L3 Evidence"), prompt.index("### L4 Evidence"))
        self.assertIn("### L5. Synthesis", prompt)
        self.assertIn("#### Layer Conflicts", prompt)

    def test_parse_layered_output_extracts_layers_and_synthesis(self) -> None:
        text = """### L0. Signal Quality Gate
- all leads reliable

### L1. Rhythm
- sinus rhythm 72 bpm

### L2. Conduction & Intervals
- PR 160ms normal

### L3. Axis & Chamber Morphology
- normal axis

### L4. ST-T / Ischemia & Infarction
- no pathological Q waves

### L5. Synthesis
#### Most Likely Diagnosis
- Normal ECG

#### Diagnostic Rationale (layer references)
- All layers normal.

#### Similar Diagnoses (ranked by similarity)
1. Diagnosis: Sinus rhythm
   Shared features: normal intervals
   Key differentiator: none
2. Diagnosis: Early repolarization
   Shared features: normal QRS
   Key differentiator: no ST elevation
3. Diagnosis: Athletic heart
   Shared features: normal ECG
   Key differentiator: no bradycardia here

#### Layer Conflicts
- None.

#### Uncertainty and Review Priorities
- None."""

        parsed = core.parse_layered_output(text)

        self.assertEqual({"L0", "L1", "L2", "L3", "L4"}, set(parsed["layers"].keys()))
        self.assertIn("sinus rhythm 72 bpm", parsed["layers"]["L1"])
        self.assertEqual("Normal ECG", parsed["top1_raw"])
        self.assertEqual(3, len(parsed["similar_raw"]))
        self.assertIn("None.", parsed["layer_conflicts"])

    def test_check_q_wave_lvh_false_positive_flags_known_pitfall(self) -> None:
        data = {
            "interpretation": {
                "pathological_q_leads": {"V4": True, "V5": False},
                "lvh_voltage_criteria": ["sokolow_lyon"],
                "lvh_class": "probable_lvh",
                "mi_evidence": {
                    "q_by_lead": {"V4": {"significant_q": True, "q_wave_mi_ratio": False}},
                },
            }
        }

        notes = core.check_q_wave_lvh_false_positive(data)

        self.assertEqual(1, len(notes))
        self.assertIn("V4", notes[0])
        self.assertIn("false-positive old-MI", notes[0])

    def test_check_q_wave_lvh_false_positive_silent_without_lvh(self) -> None:
        data = {
            "interpretation": {
                "pathological_q_leads": {"V4": True},
                "lvh_voltage_criteria": [],
                "lvh_class": None,
                "mi_evidence": {"q_by_lead": {"V4": {"significant_q": True, "q_wave_mi_ratio": False}}},
            }
        }

        self.assertEqual([], core.check_q_wave_lvh_false_positive(data))

    def test_check_qrs_consensus_bbb_gap_flags_known_pitfall(self) -> None:
        data = {
            "global_features": {"qrs_ms": 88.0},
            "interpretation": {"qrs_width_class": "normal", "bundle_branch_block": None},
            "representative_leads": {
                "II": {"params": {"qrs_ms": 112.0}},
                "I": {"params": {"qrs_ms": 78.0}},
            },
        }

        notes = core.check_qrs_consensus_bbb_gap(data)

        self.assertEqual(1, len(notes))
        self.assertIn("II=112ms", notes[0])
        self.assertIn("undercount", notes[0])

    def test_check_qrs_consensus_bbb_gap_silent_when_bbb_already_called(self) -> None:
        data = {
            "global_features": {"qrs_ms": 130.0},
            "interpretation": {"qrs_width_class": "wide", "bundle_branch_block": "clbbb"},
            "representative_leads": {"II": {"params": {"qrs_ms": 132.0}}},
        }

        self.assertEqual([], core.check_qrs_consensus_bbb_gap(data))

    def test_run_layered_diagnosis_triggers_one_revision_when_guardrail_unaddressed(self) -> None:
        features = {
            "global_features": {"heart_rate_bpm": 60.0, "qrs_ms": 88.0},
            "interpretation": {
                "qrs_width_class": "normal",
                "bundle_branch_block": None,
                "pathological_q_leads": {},
            },
            "quality": {},
            "representative_leads": {"II": {"params": {"qrs_ms": 110.0}}},
            "groups": {},
            "metadata": {},
        }

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            features_path = root / "001_features.json"
            features_path.write_text(core.json_dumps(features), encoding="utf-8")

            first_output = (
                "### L0. Signal Quality Gate\n- ok\n\n### L1. Rhythm\n- sinus\n\n"
                "### L2. Conduction & Intervals\n- normal\n\n### L3. Axis & Chamber Morphology\n- normal\n\n"
                "### L4. ST-T / Ischemia & Infarction\n- none\n\n### L5. Synthesis\n"
                "#### Most Likely Diagnosis\n- Normal ECG\n\n#### Diagnostic Rationale (layer references)\n- ok\n\n"
                "#### Similar Diagnoses (ranked by similarity)\n"
                "1. Diagnosis: Sinus rhythm\n   Shared features: a\n   Key differentiator: b\n"
                "2. Diagnosis: Athletic heart\n   Shared features: a\n   Key differentiator: b\n"
                "3. Diagnosis: Early repol\n   Shared features: a\n   Key differentiator: b\n\n"
                "#### Layer Conflicts\n- none\n\n#### Uncertainty and Review Priorities\n- none"
            )
            calls: list[str] = []

            def fake_generate(prompt: str) -> str:
                calls.append(prompt)
                return first_output

            result = core.run_layered_diagnosis(features_path, None, "", "en", fake_generate)

        # L0-L4 are now five isolated calls, the QRS guardrail revises L2,
        # and L5 synthesis is a final independent call.
        self.assertEqual(7, len(calls))
        self.assertTrue(result["revised"])
        self.assertEqual("json_report_no_dx_sequential_v3", result["reasoning_mode"])
        self.assertEqual({"L0", "L1", "L2", "L3", "L4"}, set(result["stage_outputs"]))
        self.assertEqual(1, len(result["stage_revision_prompts"]["L2"]))
        self.assertEqual(1, len(result["guardrail_notes"]))
        self.assertIn("undercount", result["guardrail_notes"][0])

    def test_sequential_evidence_excludes_precomputed_diagnostic_labels(self) -> None:
        data = {
            "global_features": {"heart_rate_bpm": 72.0, "qrs_ms": 102.0},
            "interpretation": {
                "probable_af": True,
                "bundle_branch_block": "incomplete_RBBB",
                "pathological_q_leads": {"II": True},
                "stemi_suspected_codes": ["IMIA"],
            },
            "beats": [
                {"rr_next_ms": 830.0},
                {"rr_next_ms": 835.0},
                {"rr_next_ms": 828.0},
            ],
            "quality": {},
            "representative_leads": {},
            "groups": {},
            "metadata": {},
        }

        layers = core.summarize_layered_evidence(data, "en")
        combined = "\n".join(layers.values())

        self.assertNotIn("probable_af", combined)
        self.assertNotIn("incomplete_RBBB", combined)
        self.assertNotIn("pathological_q_leads", combined)
        self.assertNotIn("IMIA", combined)
        self.assertIn("Raw RR series", layers["L1"])
        self.assertIn("Raw per-lead QRS morphology", layers["L2"])
        self.assertIn("Raw Q/ST/T measurements", layers["L4"])

    def test_layer_prompt_is_measurement_isolated(self) -> None:
        prompt = core.build_layer_reasoning_prompt(
            "L2",
            "L2_ONLY_MEASUREMENTS",
            "L0_ONLY_QUALITY",
            "en",
        )

        self.assertIn("isolated L2 adjudication stage", prompt)
        self.assertIn("L2_ONLY_MEASUREMENTS", prompt)
        self.assertIn("L0_ONLY_QUALITY", prompt)
        self.assertNotIn("L1 Evidence", prompt)
        self.assertNotIn("L3 Evidence", prompt)
        self.assertIn("110-119 ms", prompt)

    def test_rr_outlier_guardrail_uses_raw_series(self) -> None:
        regular_with_pauses = {
            "beats": [
                {"rr_next_ms": value}
                for value in [512, 526, 524, 1602, 528, 514, 520, 1050, 542, 540, 530, 522]
            ]
        }

        notes = core.check_rr_outlier_driven_irregularity(regular_with_pauses)

        self.assertEqual(1, len(notes))
        self.assertIn("central", notes[0])
        self.assertIn("atrial fibrillation", notes[0])

    def test_guardrail_requires_adjudication_not_topic_keyword(self) -> None:
        note = (
            "pathological_q_leads with LVH voltage and q_wave_mi_ratio False "
            "may be a false-positive old-MI call"
        )
        self.assertFalse(core._guardrail_addressed(note, "L3 shows LVH voltage criteria."))
        self.assertTrue(
            core._guardrail_addressed(
                note,
                "The Q-wave Q/R ratio is confounded by LVH voltage and does not support infarction.",
            )
        )

    def test_synthesis_guardrails_reject_unsupported_irbbb_and_prior_mi(self) -> None:
        data = {
            "global_features": {"qrs_ms": 102.0},
            "representative_leads": {
                lead: {
                    "params": {
                        "q_duration_ms": 20.0,
                        "q_amp_mv": -0.1,
                    }
                }
                for lead in core.STANDARD_12_LEADS
            },
        }
        parsed = {
            "top1_raw": "Sinus rhythm with IRBBB and prior inferior myocardial infarction"
        }

        notes = core.run_synthesis_guardrails(data, parsed, "")

        self.assertEqual(2, len(notes))
        self.assertTrue(any("110-119" in note for note in notes))
        self.assertTrue(any("Q duration" in note for note in notes))

    def test_sequential_pipeline_composes_six_independent_calls(self) -> None:
        features = {
            "global_features": {"heart_rate_bpm": 58.0, "qrs_ms": 88.0},
            "interpretation": {},
            "quality": {},
            "representative_leads": {},
            "groups": {},
            "beats": [
                {"rr_next_ms": 1030.0},
                {"rr_next_ms": 1020.0},
                {"rr_next_ms": 1040.0},
            ],
            "metadata": {},
        }
        calls: list[str] = []

        def fake_generate(prompt: str) -> str:
            calls.append(prompt)
            if "final ECG synthesis adjudicator" in prompt:
                return """#### Most Likely Diagnosis
- Sinus bradycardia

#### Diagnostic Rationale (layer references)
- L1 shows 58 bpm with regular RR intervals.

#### Similar Diagnoses (ranked by similarity)
1. Diagnosis: Normal sinus rhythm
   Shared features: organized rhythm
   Key differentiator: rate below 60 bpm
2. Diagnosis: Junctional rhythm
   Shared features: bradycardia
   Key differentiator: P-wave relationship
3. Diagnosis: Sinus pause pattern
   Shared features: slow rate
   Key differentiator: no pause here

#### Layer Conflicts
- None.

#### Uncertainty and Review Priorities
- Review the tracing."""
            match = re.search(r"isolated (L[0-4]) adjudication", prompt)
            layer = match.group(1) if match else "L?"
            return f"""#### Findings
- {layer} measurements reviewed.

#### Counterevidence
- None.

#### Conclusion
- {layer} conclusion.

#### Confidence
- moderate."""

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "case_features.json"
            path.write_text(core.json_dumps(features), encoding="utf-8")
            result = core.run_layered_diagnosis(
                path,
                None,
                "",
                "en",
                fake_generate,
                max_revision_rounds=0,
            )

        self.assertEqual(6, len(calls))
        self.assertEqual("Sinus bradycardia", result["parsed"]["top1_raw"])
        self.assertEqual({"L0", "L1", "L2", "L3", "L4"}, set(result["parsed"]["layers"]))
        self.assertFalse(result["supplementary_report_used_in_reasoning"])
        self.assertIn("L0 conclusion", calls[1])
        self.assertNotIn("L1 conclusion", calls[2])

    def test_validated_measurement_facts_apply_basic_adult_thresholds(self) -> None:
        data = {
            "global_features": {
                "heart_rate_bpm": 56.0,
                "pr_ms": 131.0,
                "qrs_ms": 104.0,
                "qtc_bazett_ms": 482.0,
                "qtc_fridericia_ms": 488.0,
                "qrs_axis_deg": -49.0,
                "ptf_v1_mv_ms": -0.3,
            },
            "representative_leads": {},
            "metadata": {"patient_meta": {"sex": "Male", "age": 78}},
        }

        facts = core.build_validated_measurement_facts(data)

        self.assertIn("bradycardic", facts["L1"])
        self.assertIn("does not support first-degree", facts["L2"])
        self.assertIn("QTcB 482 ms => prolonged", facts["L2"])
        self.assertIn("left axis deviation", facts["L3"])

    def test_stage_claim_guardrails_reject_direct_numeric_contradictions(self) -> None:
        data = {
            "global_features": {
                "heart_rate_bpm": 56.0,
                "pr_ms": 131.0,
                "qtc_bazett_ms": 482.0,
                "qtc_fridericia_ms": 488.0,
                "qrs_axis_deg": -49.0,
                "ptf_v1_mv_ms": -0.3,
            },
            "representative_leads": {
                "V1": {"params": {"t_amp_mv": 0.2, "t_polarity_observed": 1}},
                "V2": {"params": {"t_amp_mv": 0.3, "t_polarity_observed": 1}},
                "aVR": {"params": {"t_amp_mv": -0.1, "t_polarity_observed": -1}},
            },
            "metadata": {"patient_meta": {"sex": "Male"}},
        }
        outputs = {
            "L0": "quality adequate",
            "L1": "Sinus rhythm.",
            "L2": "First-degree AV block. QT interval is normal.",
            "L3": "Normal QRS axis. Possible LAE based on PTF-V1.",
            "L4": "T-wave inversion is present in V1-V2.",
        }

        notes = core.run_stage_claim_guardrails(data, outputs)

        self.assertTrue(any("bradycardia" in note for note in notes["L1"]))
        self.assertTrue(any("first-degree" in note for note in notes["L2"]))
        self.assertTrue(any("cannot be called normal" in note for note in notes["L2"]))
        self.assertTrue(any("left axis deviation" in note for note in notes["L3"]))
        self.assertTrue(any("PTF-V1" in note for note in notes["L3"]))
        self.assertTrue(any("V1, V2" in note for note in notes["L4"]))

    def test_stage_claim_guardrails_do_not_treat_negated_diagnoses_as_claims(self) -> None:
        data = {
            "global_features": {
                "heart_rate_bpm": 70.0,
                "pr_ms": 158.0,
                "qtc_bazett_ms": 410.0,
                "qtc_fridericia_ms": 405.0,
                "qrs_axis_deg": 53.0,
                "ptf_v1_mv_ms": -0.3,
            },
            "representative_leads": {},
            "metadata": {"patient_meta": {"sex": "Male"}},
        }
        outputs = {
            "L0": "Quality adequate.",
            "L1": "Normal sinus rhythm.",
            "L2": (
                "First-degree AV block is not supported. QTc is not prolonged. "
                "QT dispersion is prolonged."
            ),
            "L3": "Normal QRS axis. No right axis deviation. LAE is unsupported.",
            "L4": "No abnormality.",
        }

        notes = core.run_stage_claim_guardrails(data, outputs)

        self.assertEqual([], notes["L2"])
        self.assertEqual([], notes["L3"])

    def test_stage_and_synthesis_guardrails_reject_false_axis_deviation(self) -> None:
        data = {
            "global_features": {
                "heart_rate_bpm": 66.0,
                "pr_ms": 158.0,
                "qrs_axis_deg": 53.0,
                "qtc_bazett_ms": 410.0,
                "qtc_fridericia_ms": 405.0,
            },
            "representative_leads": {},
            "metadata": {"patient_meta": {"sex": "Male"}},
        }
        outputs = {
            "L0": "Quality adequate.",
            "L1": "Sinus rhythm.",
            "L2": "Normal intervals.",
            "L3": "Right axis deviation based on P and T axes.",
            "L4": "No abnormality.",
        }
        parsed = {
            "top1_raw": "Sinus rhythm.",
            "l5_synthesis": """#### Most Likely Diagnosis
- Sinus rhythm.
- Right axis deviation based on P and T axes.

#### Diagnostic Rationale (layer references)
- QRS axis is 53 degrees. QTcB interval is prolonged.""",
        }

        stage_notes = core.run_stage_claim_guardrails(data, outputs)
        synthesis_notes = core.run_synthesis_guardrails(data, parsed, "")

        self.assertTrue(any("within the adult" in note for note in stage_notes["L3"]))
        self.assertTrue(any("Remove the unsupported right" in note for note in synthesis_notes))
        self.assertTrue(any("unsupported prolonged-QTc" in note for note in synthesis_notes))

    def test_raw_multilead_residual_rule_supports_flutter_without_dx_fields(self) -> None:
        per_lead = {
            "II": {"dominant_cycle_ms": 214.0, "stability": 0.36, "organized_spectral_power_ratio": 0.55},
            "III": {"dominant_cycle_ms": 212.0, "stability": 0.35, "organized_spectral_power_ratio": 0.51},
            "V1": {"dominant_cycle_ms": 214.0, "stability": 0.23, "organized_spectral_power_ratio": 0.44},
        }
        data = {
            "global_features": {"heart_rate_bpm": 126.0},
            "metadata": {
                "patient_meta": {"sex": "Female"},
                "rhythm_analysis": {"atrial_residual": {"per_lead_atrial_activity": per_lead}},
            },
            "representative_leads": {},
        }

        facts = core.build_validated_measurement_facts(data)
        notes = core.run_stage_claim_guardrails(
            data,
            {"L0": "Adequate.", "L1": "Sinus tachycardia.", "L2": "", "L3": "", "L4": ""},
        )

        self.assertIn("strict multilead support=True", facts["L1"])
        self.assertIn("atrial-flutter ECG pattern", facts["L1"])
        self.assertTrue(any("sinus tachycardia alone" in note for note in notes["L1"]))

    def test_json_report_reasoning_uses_measurements_but_never_dx(self) -> None:
        features = {
            "global_features": {
                "heart_rate_bpm": 72.0,
                "pr_ms": 160.0,
                "qrs_ms": 90.0,
                "qtc_bazett_ms": 410.0,
                "qtc_fridericia_ms": 405.0,
                "qrs_axis_deg": 20.0,
            },
            "interpretation": {},
            "quality": {},
            "representative_leads": {},
            "groups": {},
            "beats": [],
            "metadata": {"patient_meta": {"age": 50, "sex": "Male"}},
        }
        report = """  ───  PATIENT INFORMATION  ─────────────────────
  Dx Codes      : 164890007
  Dx Detail     : Atrial flutter
  Age           : 50

  ───  GLOBAL MEASUREMENTS  ─────────────────────
  Heart Rate    : 72 bpm
  PR Interval   : 160 ms

  ───  RHYTHM SUMMARY  ──────────────────────────
  Atrial classification : atrial_flutter
  Mean RR interval      : 833 ms

  ───  UNIFIED CLINICAL INTERPRETATION  ─────────
  CLIN-RHYTHM-AFL-01 : ECG pattern consistent with atrial flutter
"""

        def fake_generate(prompt: str) -> str:
            if "final ECG synthesis adjudicator" in prompt:
                return """#### Most Likely Diagnosis
- Normal sinus rhythm

#### Diagnostic Rationale (layer references)
- Measurements are normal.

#### Similar Diagnoses (ranked by similarity)
1. Diagnosis: Sinus rhythm
   Shared features: regular
   Key differentiator: none
2. Diagnosis: Ectopic atrial rhythm
   Shared features: atrial activity
   Key differentiator: axis
3. Diagnosis: Junctional rhythm
   Shared features: regular
   Key differentiator: P waves

#### Layer Conflicts
- None.

#### Uncertainty and Review Priorities
- None."""
            return """#### Findings
- Measurements reviewed.

#### Counterevidence
- None.

#### Conclusion
- No abnormality in this stage.

#### Confidence
- high."""

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            features_path = root / "case_features.json"
            report_path = root / "case_report.txt"
            features_path.write_text(core.json_dumps(features), encoding="utf-8")
            report_path.write_text(report, encoding="utf-8")
            result = core.run_layered_diagnosis(
                features_path,
                report_path,
                "",
                "en",
                fake_generate,
                max_revision_rounds=0,
            )

        prompt_text = "\n".join(result["stage_prompts"].values())
        self.assertTrue(result["supplementary_report_used_in_reasoning"])
        self.assertFalse(result["dx_code_used_in_reasoning"])
        self.assertIn("Heart Rate    : 72 bpm", prompt_text)
        self.assertNotIn("164890007", prompt_text)
        self.assertNotIn("Atrial flutter", prompt_text)
        self.assertNotIn("atrial_flutter", prompt_text)
        self.assertNotIn("CLIN-RHYTHM-AFL-01", prompt_text)

    def test_clean_model_output_removes_hidden_reasoning_tokens(self) -> None:
        raw = "before<unused94>thought\nprivate reasoning<unused95>#### Findings\n- visible"
        cleaned = core.clean_model_output(raw)

        self.assertNotIn("private reasoning", cleaned)
        self.assertNotIn("unused", cleaned)
        self.assertIn("#### Findings", cleaned)


if __name__ == "__main__":
    unittest.main()
