#!/usr/bin/env python3
"""Generate the reference documentation from the installed packages.

docs/library_design/07_packaging_and_release.md, "Documentation site": API
pages come from importable public objects and their docstrings, and the
schema/validation reference from the exact schema, registry and crosswalk
files the ``ecgfeat`` package ships.  ``--check`` regenerates into memory and
fails if the committed pages differ (run in CI against the wheel candidate).
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import json
import sys
import warnings
from importlib import resources
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "site" / "reference"
HEADER = "<!-- Generated by tools/build_docs.py from the installed packages; do not edit by hand. -->\n\n"


def _first_paragraph(obj) -> str:
    doc = inspect.getdoc(obj) or ""
    return doc.split("\n\n", 1)[0].replace("\n", " ").strip()


def _signature(obj) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return ""


def api_page(module_name: str, names, title: str, legacy=()) -> str:
    module = importlib.import_module(module_name)
    lines = [HEADER, f"# {title}\n\n", f"Module `{module_name}`"]
    version = getattr(module, "__version__", None)
    lines.append(f" — version `{version}`.\n\n" if version else ".\n\n")
    lines.append("| Name | Kind | Signature | Summary |\n|---|---|---|---|\n")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        for name in names:
            obj = getattr(module, name)
            kind = "class" if inspect.isclass(obj) else "function" if callable(obj) else "constant"
            signature = _signature(obj) if kind != "constant" else f"= `{obj!r}`"
            signature = signature.replace("|", "\\|")
            summary = _first_paragraph(obj).replace("|", "\\|") if kind != "constant" else ""
            lines.append(f"| `{name}` | {kind} | `{signature}` | {summary} |\n" if kind != "constant"
                         else f"| `{name}` | constant | {signature} | |\n")
    if legacy:
        lines.append("\n## Deprecated legacy names\n\nKept for the compatibility window; functions warn on use "
                     "(`ECGDeprecationWarning`) and are removed no earlier than 0.3.0. `ecgfeat.compat` "
                     "provides the exact legacy contract without warnings.\n\n")
        lines.append("".join(f"- `{name}`\n" for name in legacy))
    return "".join(lines)


def _resource(package: str, *parts: str) -> str:
    return resources.files(package).joinpath(*parts).read_text(encoding="utf-8")


def schema_page() -> str:
    schema = json.loads(_resource("ecgfeat", "schemas", "ecg-record", "1.0", "schema.json"))
    registry = json.loads(_resource("ecgfeat", "schemas", "ecg-record", "1.0", "validation-evidence.json"))
    from ecgfeat.pipeline.record_builder import SCHEMA_VERSION

    lines = [HEADER, "# ECG Record schema 1.0 — field reference\n\n",
             f"Emitted schema version: `{SCHEMA_VERSION}`. Readers accept schema major `1`. JSON Schema: "
             f"`ecgfeat/schemas/ecg-record/1.0/schema.json` (`$id` `{schema.get('$id', '')}`).\n\n",
             "Validation tiers come only from the shipped registry "
             "(`validation-evidence.json`); a field can claim more than `unvalidated` only by citing an "
             "evidence manifest (see `tools/check_validation_registry.py`).\n\n",
             "## Published fields\n\n",
             "| Pointer | Profiles | Publication | Validation (ceiling) | Legacy source | Known limitations |\n",
             "|---|---|---|---|---|---|\n"]
    for entry in registry["fields"]:
        limitations = " ".join(entry["known_limitations"]).replace("|", "\\|") or "—"
        lines.append(f"| `{entry['pointer']}` | {', '.join(entry['profiles'])} | {entry['publication_tier']} | "
                     f"{entry['validation_tier']} ({entry['validation_ceiling']}) | `{entry['legacy_source']}` | "
                     f"{limitations} |\n")
    lines.append("\n## Debug-only and capped quantities\n\n| Quantity | Tier | Ceiling | Reason |\n|---|---|---|---|\n")
    for entry in registry["debug_caps"]:
        lines.append(f"| `{entry['pointer']}` | {entry['publication_tier']} | {entry['validation_ceiling']} | "
                     f"{' '.join(entry['known_limitations'])} |\n")
    for pattern in registry.get("debug_patterns", []):
        lines.append(f"| `{pattern['pattern']}` | {pattern['publication_tier']} | {pattern['validation_ceiling']} | "
                     f"{pattern['reason']} |\n")
    lines.append("\n## Top-level members\n\n| Member | Required |\n|---|---|\n")
    required = set(schema.get("required", []))
    for member in schema.get("properties", {}):
        lines.append(f"| `{member}` | {'yes' if member in required else 'no'} |\n")
    lines.append("\n## Absence states\n\nPlain `null` (no stronger claim), `unmeasurable(reason)` and "
                 "`not_applicable(reason)`. Dense fields encode reasons as a whole-field `{kind, reason}`, "
                 "a per-field `default` state, and sparse `<beat_id>|<lead>` maps that override it.\n")
    return "".join(lines)


def crosswalk_page() -> str:
    crosswalk = json.loads((ROOT / "schemas" / "ecg-record" / "1.0" / "crosswalk-legacy-v0.json").read_text())
    lines = [HEADER, "# Legacy export → ECG Record crosswalk\n\n",
             "How each value of the legacy `to_dict` export maps to an ECG Record address "
             "(`ecg-record:<record_id>@<schema_version>#<pointer>`). Source: "
             "`schemas/ecg-record/1.0/crosswalk-legacy-v0.json`, the same table the parity gate uses.\n\n",
             "## Per-beat, per-lead fields\n\n| Record pointer | Legacy member of `beat_features[*]` | Transform | Profiles |\n",
             "|---|---|---|---|\n"]
    for rule in crosswalk["dense_fields"]:
        lines.append(f"| `{rule['record']}` | `{rule['legacy_cell_member']}` | {rule['transform']} | "
                     f"{', '.join(rule['profiles'])} |\n")
    lines.append("\n## Record-level fields\n\n| Record pointer | Legacy pointer | Transform |\n|---|---|---|\n")
    for rule in crosswalk["scalar_fields"] + crosswalk["other_mapped"]:
        lines.append(f"| `{rule['record']}` | `{rule['legacy']}` | {rule['transform']} |\n")
    lines.append("\n## Transforms\n\n" + "".join(f"- **{k}**: {v}\n" for k, v in crosswalk["transforms"].items()))
    lines.append("\n## Legacy sections without a record 1.0 equivalent\n\n"
                 + "".join(f"- `{k}`: {v}\n" for k, v in crosswalk["legacy_section_dispositions"].items()))
    return "".join(lines)


def interpretation_schema_page() -> str:
    schema = json.loads(_resource("ecginterpret", "schemas", "interpretation", "1.0", "schema.json"))
    import ecginterpret

    lines = [HEADER, "# Interpretation document 1.0\n\n",
             f"Produced by `ecginterpret` `{ecginterpret.__version__}`; schema version "
             f"`{ecginterpret.INTERPRETATION_SCHEMA_VERSION}` (independent of the ECG Record schema). "
             f"{schema.get('description', '')}\n\n| Member | Required | Description |\n|---|---|---|\n"]
    required = set(schema["required"])
    for name, spec in schema["properties"].items():
        lines.append(f"| `{name}` | {'yes' if name in required else 'no'} | {spec.get('description', '')} |\n")
    return "".join(lines)


def pages() -> dict[str, str]:
    import ecgfeat

    return {
        "api-ecgfeat.md": api_page("ecgfeat", ecgfeat.PUBLIC_API, "ecg-records API (`ecgfeat`)", ecgfeat.LEGACY_API),
        "api-ecginterpret.md": api_page("ecginterpret", [n for n in importlib.import_module("ecginterpret").__all__
                                                          if n != "__version__"], "ecginterpret API"),
        "api-ecgrecords-viz.md": api_page("ecgrecords_viz", [n for n in importlib.import_module("ecgrecords_viz").__all__
                                                              if n != "__version__"], "ecg-records-viz API"),
        "ecg-record-schema-1.0.md": schema_page(),
        "legacy-crosswalk.md": crosswalk_page(),
        "interpretation-schema-1.0.md": interpretation_schema_page(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed pages differ")
    args = parser.parse_args(argv)
    generated = pages()
    if args.check:
        stale = [name for name, text in generated.items()
                 if not (OUT / name).exists() or (OUT / name).read_text(encoding="utf-8") != text]
        for name in stale:
            print(f"stale: docs/site/reference/{name}")
        print(f"{len(generated) - len(stale)}/{len(generated)} reference pages current")
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in generated.items():
        (OUT / name).write_text(text, encoding="utf-8")
    print(f"wrote {len(generated)} pages to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
